#include<iostream>
#include<stdio.h>
#include<stdlib.h>
#include<string>
#include<string.h>
#include<math.h>
#include<algorithm>
using namespace std;
void qsort(int l,int r,int a[],int b[])
{
     int i,j,mid;
     i=l;
     j=r;
     mid=a[(l+r)/2];
     while(i<=j)
     {
       while(a[i]<mid)
         i++;
       while(a[j]>mid)
         j--;
       if(i<=j)
       {
         swap(a[i],a[j]);
         swap(b[i],b[j]);
         i++;
         j--;
       }
     }
     if(i<r)
       qsort(i,r,a,b);
     if(l<j)
       qsort(l,j,a,b);
}
int main()
{
    freopen("game.in","r",stdin);
    freopen("game.out","w",stdout);
    int i,j,k,n,a[1001],b[1001];
    double c,tot,minc,ans=1;
    scanf("%d",&n);
    for(i=0;i<=n;i++)
    {
      scanf("%d%d",&a[i],&b[i]);
      ans=ans*a[i];
    }
    qsort(1,n,a,b);
    for(i=n;i>=n/2;i--)
    {
      c=ans/a[i]/b[i];
      for(j=n-1;j>=n/10+1;j--)
      {
        tot=1;
        for(k=0;k<=j-1;k++)
          tot=tot*a[k];
        c=max(c,tot/b[j]);
      }
      if(i==n)
        minc=c;
      else
        if(minc>c)
          minc=c;
    }
    qsort(1,n,b,a);
    for(i=n;i>=n/2;i--)
    {
      c=ans/a[i]/b[i];
      for(j=n-1;j>=n/10+1;j--)
      {
        tot=1;
        for(k=0;k<=j-1;k++)
          tot=tot*a[k];
        c=max(c,tot/b[j]);
      }
      if(minc>c)
        minc=c;
    }
    printf("%.0lf\n",minc);
    fclose(stdin);
    fclose(stdout);
    return 0;
}
