#include<iostream>
#include<stdio.h>
#include<cmath>
#include<cstring>
#include<algorithm>
#include<stdlib.h>
#include<string>
using namespace std;
int main()
{
    freopen("flower.in","r",stdin);
    freopen("flower.out","w",stdout);
    int mid,i,n,ans,max1,max2;
    int h[100001]={},l[100001]={};
    int a[100001]={};
    cin>>n;
    for(i=1;i<=n;i++)
    scanf("%d",&a[i]);
    h[1]=a[1];
    ans=1;
    mid=-1;
    for(i=2;i<=n;i++)
    {
    if(mid==-1)
    {if(a[i]<h[ans])
    mid=a[i];
    if(a[i]>h[ans])
    h[ans]=a[i];
    }
    else
    {if(a[i]<mid)
    mid=a[i];
    if(a[i]>mid)
    {
    ans++;
    h[ans]=a[i];
    mid=-1;
    }
    }
    }
    if(mid==-1)
    max1=2*ans-1;
    else
    max1=2*ans;
    l[1]=a[1];
    ans=1;
    mid=-1;
    for(i=2;i<=n;i++)
    {
    if(mid==-1)
    {if(a[i]>l[ans])
    mid=a[i];
    if(a[i]<l[ans])
    l[ans]=a[i];
    }
    else
    {if(a[i]>mid)
    mid=a[i];
    if(a[i]<mid)
    {
    ans++;
    l[ans]=a[i];
    mid=-1;
    }
    }
    }
    if(mid==-1)
    max2=2*ans-1;
    else
    max2=2*ans;
    if(max1>max2)
    cout<<max1<<'\n';
    else
    cout<<max2<<'\n';
    fclose(stdin);
    fclose(stdout);
    return 0;
}
