#include<iostream>
#include<stdio.h>
#include<stdlib.h>
#include<math.h>
#include<string.h>
#include<algorithm>
using namespace std;
int n,m,x[1001],a[1001][1001],p=1;
int main()
{
    freopen("level.in","r",stdin);
    freopen("level.out","w",stdout);
    int i,j,k,l,t;
    scanf("%d%d",&n,&m);
    for(i=1;i<=n;i++)
      x[i]=1;
    for(i=1;i<=m;i++)
      {
       scanf("%d",&a[i][0]);
       for(j=1,l=0;j<=a[i][0];j++)
         {
          scanf("%d",&a[i][j]);
          if(x[a[i][j]]>l)
            l=x[a[i][j]];
         }
       for(j=1,t=0;j<a[i][0];j++)
         for(k=a[i][j]+1;k<a[i][j+1];k++)
           if(x[k]<=l)
             x[k]=l+1;
      }
    for(i=m;i>=1;i--)
      {
       for(j=1,l=0;j<=a[i][0];j++)
         if(x[a[i][j]]>l)
           l=x[a[i][j]];
       for(j=1,t=0;j<a[i][0];j++)
         for(k=a[i][j]+1;k<a[i][j+1];k++)
           if(x[k]<=l)
             x[k]=l+1;
      }
    for(i=1;i<=m;i++)
      {
       for(j=1,l=0;j<=a[i][0];j++)
         if(x[a[i][j]]>l)
           l=x[a[i][j]];
       for(j=1,t=0;j<a[i][0];j++)
         for(k=a[i][j]+1;k<a[i][j+1];k++)
           if(x[k]<=l)
             x[k]=l+1;
      }
    for(i=m;i>=1;i--)
      {
       for(j=1,l=0;j<=a[i][0];j++)
         if(x[a[i][j]]>l)
           l=x[a[i][j]];
       for(j=1,t=0;j<a[i][0];j++)
         for(k=a[i][j]+1;k<a[i][j+1];k++)
           if(x[k]<=l)
             x[k]=l+1;
      }
    for(i=1;i<=m;i++)
      {
       for(j=1,l=0;j<=a[i][0];j++)
         if(x[a[i][j]]>l)
           l=x[a[i][j]];
       for(j=1,t=0;j<a[i][0];j++)
         for(k=a[i][j]+1;k<a[i][j+1];k++)
           if(x[k]<=l)
             x[k]=l+1;
      }
    for(i=m;i>=1;i--)
      {
       for(j=1,l=0;j<=a[i][0];j++)
         if(x[a[i][j]]>l)
           l=x[a[i][j]];
       for(j=1,t=0;j<a[i][0];j++)
         for(k=a[i][j]+1;k<a[i][j+1];k++)
           if(x[k]<=l)
             x[k]=l+1;
      }
    for(i=1;i<=m;i++)
      {
       for(j=1,l=0;j<=a[i][0];j++)
         if(x[a[i][j]]>l)
           l=x[a[i][j]];
       for(j=1,t=0;j<a[i][0];j++)
         for(k=a[i][j]+1;k<a[i][j+1];k++)
           if(x[k]<=l)
             x[k]=l+1;
      }
    for(i=1;i<=n;i++)
      if(x[i]>p)
        p=x[i];
    printf("%d\n",p);
    fclose(stdin);
    fclose(stdout);
    return 0;
}
