D:\ioi2k\huangjian\Check\Check\Exe\car_f car1.out 
D:\ioi2k\huangjian\Check\Check\Exe\car_f car2.out 
D:\ioi2k\huangjian\Check\Check\Exe\car_f car3.out 
D:\ioi2k\huangjian\Check\Check\Exe\car_f car4.out 
D:\ioi2k\huangjian\Check\Check\Exe\car_f car5.out 
D:\ioi2k\huangjian\Check\Check\Exe\car_f car6.out 
D:\ioi2k\huangjian\Check\Check\Exe\car_f car7.out 
D:\ioi2k\huangjian\Check\Check\Exe\car_f car8.out 
D:\ioi2k\huangjian\Check\Check\Exe\car_f car9.out 
D:\ioi2k\huangjian\Check\Check\Exe\car_f car10.out
pause