D:\ioi2k\huangjian\Filter\Filter\Exe\car_fpf car1.out car1.ans
D:\ioi2k\huangjian\Filter\Filter\Exe\car_fpf car2.out car2.ans
D:\ioi2k\huangjian\Filter\Filter\Exe\car_fpf car3.out car3.ans
D:\ioi2k\huangjian\Filter\Filter\Exe\car_fpf car4.out car4.ans
D:\ioi2k\huangjian\Filter\Filter\Exe\car_fpf car5.out car5.ans
D:\ioi2k\huangjian\Filter\Filter\Exe\car_fpf car6.out car6.ans
D:\ioi2k\huangjian\Filter\Filter\Exe\car_fpf car7.out car7.ans
D:\ioi2k\huangjian\Filter\Filter\Exe\car_fpf car8.out car8.ans
D:\ioi2k\huangjian\Filter\Filter\Exe\car_fpf car9.out car9.ans
D:\ioi2k\huangjian\Filter\Filter\Exe\car_fpf car10.out car10.ans
pause