#include<iostream>
#include<algorithm>
#include<stdlib.h>
#include<stdio.h>
#include<math.h>
#include<string>
#include<string.h>
using namespace std;
int main(){
    freopen("expr.in","r",stdin);
    freopen("expr.out","w",stdout);
    char n[100];
    cin>>n;
    int i,j=1,k,l=0,m,o=0,p=0,q;
    char a[100],b[100],c[100],e[100],f[100];
    memset(e,0,sizeof(char));
    memset(f,0,sizeof(char));
    memset(a,0,sizeof(char));
    memset(b,0,sizeof(char));
    b[0]=-1;
    for(i=1;i<100;i++){
        if(n[i]=='+'){
            a[j]='+';
            b[j]=i; 
            j++;
            }   
        if(n[i]=='*'){
            a[j]=='*';
            b[j]=i;
            j++;
            } 
        }
    for(i=1;i<100;i++){
        if(a[i]=='*'){
            for(k=b[i-1]+1;k<=b[i]-1;k++,o++){
                f[100-o]=(n[k]*f[100-o]%10)+p;
                p=(n[k]*f[100-o])/10;
                }
            o=0;
            p=0;
            for(k=b[i]+1;k<=b[i+1]-1;k++,o++){
                f[100-o]=(n[k]*f[100-o]%10)+p;
                p=(n[k]*f[100-o])/10;
                }
            p=0;
            o=0;
            for(q=i;1<100;q++){
            a[q]=a[q+1];
            b[q]=b[q+1];
            }
                                   }
                       }
    for(i=1;i<100;i++){
            for(k=b[i-1]+1;k<=b[i]-1;k++,o++)
                f[100-o]=n[k]+f[100-o];
            o=0;
            for(k=b[i]+1;k<=b[i+1]-1;k++,o++)
                f[100-o]=n[k]+f[100-o];
            o=0;
            for(q=i;1<100;q++){
            a[q]=a[q+1];
            b[q]=b[q+1];
            }    
            }                        
        if(f[3]!=0)
            cout<<f[i];
        else
            if(f[2]!=0)
                cout<<f[i];
            else
                if(f[1]!=0)
                    cout<<f[i];
                else
                    cout<<f[0];
                       
    fclose(stdin);
    fclose(stdout);
    return 0;
    }
