var
   a,b,c,d,s:integer;
begin
   assign(input,'circle.in');
   reset(input);
   assign(output,'circle.out');
   rewrite(output);
   readln(a,b,c,d);
   s:=d;
   close(input);
   writeln(d);
   close(output);
end.
