#include<stdio.h>
#define MIN(a,b)a<b?a:b
int n,m,q,v[35][35]={0};//v[]记录障碍位置
int vis[31][31][31][31]={0};//vis[i][j][x][y]表示空格在（i,j）指定棋子在（x,y） 
int a,b,c,d,fx,fy,min=999999;
void seek(int ex,int ey,int sx,int sy,int x)
{
     int i,j;
     if(sx==fx&&sy==fy){min=MIN(min,x);return;}
     if(x==min)return;//如果不够优，掐掉 
     if(ey<m&&v[ex][ey+1]==0)
     {
         if(ex==sx&&ey+1==sy)//如果和指定棋子交换位置
         { 
             if(vis[sx][sy][ex][ey]==0)
             {
                 vis[ex][ey+1][ex][ey]=1;
                 seek(ex,ey+1,ex,ey,x+1);
                 vis[ex][ey+1][ex][ey]=0;
             }
         }
         else
         {
             if(vis[ex][ey+1][sx][sy]==0)
             {
                 vis[ex][ey+1][sx][sy]=1;
                 seek(ex,ey+1,sx,sy,x+1);
                 vis[ex][ey+1][sx][sy]=0;
             }
         }
     }
     if(ey>1&&v[ex][ey-1]==0)
     {
         if(ex==sx&&ey-1==sy)
         {
             if(vis[ex][ey-1][ex][ey]==0)
             {
                 vis[ex][ey-1][ex][ey]=1;
                 seek(ex,ey-1,ex,ey,x+1);
                 vis[ex][ey-1][ex][ey]=0;
             }
         }
         else
         {
             if(vis[ex][ey-1][sx][sy]==0)
             {
                 vis[ex][ey-1][sx][sy]=1;
                 seek(ex,ey-1,sx,sy,x+1);
                 vis[ex][ey-1][sx][sy]=0;
             }
         }
     }
     if(ex<n&&v[ex+1][ey]==0)
     {
         if(ex+1==sx&&ey==sy)
         {
             if(vis[ex+1][ey][ex][ey]==0)
             {
                 vis[ex+1][ey][ex][ey]=1;
                 seek(ex+1,ey,ex,ey,x+1);
                 vis[ex+1][ey][ex][ey]=0;
             }
         }
         else
         {
             if(vis[ex+1][ey][sx][sy]==0)
             {
                 vis[ex+1][ey][sx][sy]=1;
                 seek(ex+1,ey,sx,sy,x+1);
                 vis[ex+1][ey][sx][sy]=0;
             }
         }
     }
     if(ex>1&&v[ex-1][ey]==0)
     {
         if(ex-1==sx&&ey==sy)
         {
             if(vis[ex-1][ey][ex][ey]==0)
             {
                 vis[ex-1][ey][ex][ey]=1;
                 seek(ex-1,ey,ex,ey,x+1);
                 vis[ex-1][ey][ex][ey]=0;
             }
         }
         else
         {
             if(vis[ex-1][ey][sx][sy]==0)
             {
                 vis[ex-1][ey][sx][sy]=1;
                 seek(ex-1,ey,sx,sy,x+1);
                 vis[ex-1][ey][sx][sy]=0;
             }
         }
     }
}
int main()
{
    freopen("puzzle.in","r",stdin);
    freopen("puzzle.out","w",stdout);
    int i,j,k;
    scanf("%d%d%d",&n,&m,&q);
    for(i=1;i<=n;i++)
    for(j=1;j<=m;j++)
    {
        scanf("%d",&k);
        if(k==0)v[i][j]=1;
    }
    for(i=1;i<=q;i++)
    {
        scanf("%d%d%d%d%d%d",&a,&b,&c,&d,&fx,&fy);
        min=999999;
        vis[a][b][c][d]=1;
        seek(a,b,c,d,0);
        vis[a][b][c][d]=0;
        if(min!=999999)printf("%d\n",min);
        else printf("-1\n");
    }
    //while(1);
    return 0;
}
