#include<iostream>
#include<stdio.h>
#include<stdlib.h>
#include<math.h>
#include<algorithm>
#include<string>
#include<string.h>
using namespace std;
int i,n,s=0,t=1,minh=10001,h[100001];
long long ans;
bool p,f[100001];
int main()
{
    freopen("block.in","r",stdin);
    freopen("block.out","w",stdout);
    scanf("%d",&n);
    for(i=1;i<=n;i++)
    {
      scanf("%d",&h[i]);
      if(h[i]>0)
      {
        f[i]=true;
        s++;
      }
      else
      {
        f[i]=false;
        if(i!=1&&i!=n&&f[i-1]==true)
          t++;
      }
      if(h[i]<minh&&f[i]==true)
        minh=h[i];
    }
    ans=t*minh;
    for(i=1;i<=n;i++)
      if(f[i]==true)
      {
        h[i]=h[i]-minh;
        if(h[i]==0)
        {
          f[i]=false;
          s--;
        }
      }
    while(s>0)
    {
      p=true;
      for(i=1;i<=n;i++)
      {
        if(f[i]==true&&p==true)
        {
          ans++;
          p=false;
          h[i]--;
          if(h[i]==0)
          {
            f[i]=false;
            s--;
          }
        }
        else
          if(f[i]==true&&p==false)
          {
            h[i]--;
            if(h[i]==0)
            {
              f[i]=false;
              s--;
            }
          }
          else
            if(f[i]==false&&p==false)
              p=true;
      }
    }
    printf("%lld\n",ans);
    fclose(stdin);
    fclose(stdout);
    return 0;
}
