#include<iostream>
#include<cstdlib>
#include<cstring>
#include<string>
#include<cstdio>
#include<cmath>
#include<algorithm>
using namespace std;
char c[2500000];
int l,i,b,sum,a,j,k;
int main()
{
  freopen("expr.in","r",stdin);
  freopen("expr.out","w",stdout);
  gets(c);
  l=strlen(c);
  while(c[j]<=57&&c[j]>=48)
  {
	sum=sum*10+c[j]-48;
	j++;
  }
  sum=sum%10000;
  i=j;
  while(i!=l)
  {
	j=i;
	if(c[j]=='*')
	{
	  j++;a=0;
	  while(c[j]<=57&&c[j]>=48&&j<l)
	  {
		a=a*10+c[j]-48;
		j++;
	  }
	  a=a%10000;
	  if(j==l)
	  {
	    sum=sum*a;
	    sum=sum%10000;
	    printf("%d\n",sum);
	    return 0;
	  }
	  sum=sum*a;
	  sum=sum%10000;
	  i=j;
	}
	if(c[j]=='+')
	{
	  j++;a=0;
	  while(c[j]<=57&&c[j]>=48&&j<l)
	  {
		a=a*10+c[j]-48;
		j++;
	  }
	  a=a%10000;
	  if(j==l)
	  {
	    sum=sum+a;
	    sum=sum%10000;
	    printf("%d\n",sum);
	    return 0;
	  }
	  k=j;
	  if(c[j]=='*')
	  {
		b=0;
		k++;
		while(c[k]<=57&&c[k]>=48&&k<l)
	    {
		  b=b*10+c[k]-48;
		  k++;
	    }
	    b=b%10000;
	    if(k==l)
	    {
	      a=a*b;
	      a=a%10000;
	      sum=sum+a;
	      sum=sum%10000;
	      printf("%d\n",sum);
	      return 0;
	    }
	    a=a*b;
	    a=a%10000;
	  }
	  while(c[k]!='+')
	  {
		k++;b=0;
		while(c[k]<=57&&c[k]>=48&&k<l)
	    {
		  b=b*10+c[k]-48;
		  k++;
	    }
	    b=b%10000;
	    if(k==l)
	    {
	      a=a*b;
	      a=a%10000;
	      sum=sum+a;
	      sum=sum%10000;
	      printf("%d\n",sum);
	      return 0;
	    }
	    a=a*b;
	    a=a%10000;
	  }
	  j=k;
	  sum=sum+a;
	  sum=sum%10000;
	}
	i=j;
  }
  sum=sum%10000;
  printf("%d\n",sum);
  return 0;
}
